

// \workspace\lichee\linux-4.9\include\video\sunxi_display2.h
#ifndef __UX360_LCD_H__
#define __UX360_LCD_H__


enum tag_DISP_CMD {
	/* ----disp global---- */
	DISP_RESERVE0 = 0x00,
	DISP_RESERVE1 = 0x01,
	DISP_SET_BKCOLOR = 0x03,
	DISP_GET_BKCOLOR = 0x04,
	DISP_SET_COLORKEY = 0x05,
	DISP_GET_COLORKEY = 0x06,
	DISP_GET_SCN_WIDTH = 0x07,
	DISP_GET_SCN_HEIGHT = 0x08,
	DISP_GET_OUTPUT_TYPE = 0x09,
	DISP_SET_EXIT_MODE = 0x0A,
	DISP_VSYNC_EVENT_EN = 0x0B,
	DISP_BLANK = 0x0C,
	DISP_SHADOW_PROTECT = 0x0D,
	DISP_HWC_COMMIT = 0x0E,
	DISP_DEVICE_SWITCH = 0x0F,
	DISP_GET_OUTPUT = 0x10,
	DISP_SET_COLOR_RANGE = 0x11,
	DISP_GET_COLOR_RANGE = 0x12,
	DISP_HWC_CUSTOM = 0x13,
	DISP_DEVICE_SET_CONFIG = 0x14,
	DISP_DEVICE_GET_CONFIG = 0x15,

	/* ----layer---- */
	DISP_LAYER_ENABLE = 0x40,
	DISP_LAYER_DISABLE = 0x41,
	DISP_LAYER_SET_INFO = 0x42,
	DISP_LAYER_GET_INFO = 0x43,
	DISP_LAYER_TOP = 0x44,
	DISP_LAYER_BOTTOM = 0x45,
	DISP_LAYER_GET_FRAME_ID = 0x46,
	DISP_LAYER_SET_CONFIG = 0x47,
	DISP_LAYER_GET_CONFIG = 0x48,
	/*
	 * LAYER_S(G)ET_CONFIG2 takes disp_layer_config2,
	 * it will support more featuras
	 */
	DISP_LAYER_SET_CONFIG2 = 0x49,
	DISP_LAYER_GET_CONFIG2 = 0x4a,

	/* ----hdmi---- */
	DISP_HDMI_SUPPORT_MODE = 0xc4,
	DISP_SET_TV_HPD = 0xc5,
	DISP_HDMI_GET_EDID = 0xc6,
	DISP_CEC_ONE_TOUCH_PLAY = 0xc7,

	/* ----lcd---- */
	DISP_LCD_ENABLE = 0x100,
	DISP_LCD_DISABLE = 0x101,
	DISP_LCD_SET_BRIGHTNESS = 0x102,
	DISP_LCD_GET_BRIGHTNESS = 0x103,
	DISP_LCD_BACKLIGHT_ENABLE = 0x104,
	DISP_LCD_BACKLIGHT_DISABLE = 0x105,
	DISP_LCD_SET_SRC = 0x106,
	DISP_LCD_SET_FPS = 0x107,
	DISP_LCD_GET_FPS = 0x108,
	DISP_LCD_GET_SIZE = 0x109,
	DISP_LCD_GET_MODEL_NAME = 0x10a,
	DISP_LCD_SET_GAMMA_TABLE = 0x10b,
	DISP_LCD_GAMMA_CORRECTION_ENABLE = 0x10c,
	DISP_LCD_GAMMA_CORRECTION_DISABLE = 0x10d,
	DISP_LCD_USER_DEFINED_FUNC = 0x10e,
	DISP_LCD_CHECK_OPEN_FINISH = 0x10f,
	DISP_LCD_CHECK_CLOSE_FINISH = 0x110,

	/*tv*/
	DISP_TV_SET_GAMMA_TABLE = 0x111,
	/* ---- capture --- */
	DISP_CAPTURE_START = 0x140,/* caputre screen and scaler to dram */
	DISP_CAPTURE_STOP = 0x141,
	DISP_CAPTURE_COMMIT = 0x142,
	DISP_CAPTURE_COMMIT2 = 0x143,
	DISP_CAPTURE_QUERY = 0x144,
	DISP_CAPTURE_EXTEND = 0x145,

	/* ---enhance --- */
	DISP_ENHANCE_ENABLE = 0x180,
	DISP_ENHANCE_DISABLE = 0x181,
	DISP_ENHANCE_GET_EN = 0x182,
	DISP_ENHANCE_SET_WINDOW = 0x183,
	DISP_ENHANCE_GET_WINDOW = 0x184,
	DISP_ENHANCE_SET_MODE = 0x185,
	DISP_ENHANCE_GET_MODE = 0x186,
	DISP_ENHANCE_DEMO_ENABLE = 0x187,
	DISP_ENHANCE_DEMO_DISABLE = 0x188,

	/* ---smart backlight --- */
	DISP_SMBL_ENABLE = 0x200,
	DISP_SMBL_DISABLE = 0x201,
	DISP_SMBL_GET_EN = 0x202,
	DISP_SMBL_SET_WINDOW = 0x203,
	DISP_SMBL_GET_WINDOW = 0x204,

	/* ---- for test */
	DISP_FB_REQUEST = 0x280,
	DISP_FB_RELEASE = 0x281,

	DISP_MEM_REQUEST = 0x2c0,
	DISP_MEM_RELEASE = 0x2c1,
	DISP_MEM_GETADR = 0x2c2,
	DISP_VDPO_SET_CONFIG = 0x2c3,

	/* --- rotation sw --- */
	DISP_ROTATION_SW_SET_ROT = 0x300,
	DISP_ROTATION_SW_GET_ROT = 0x301,

	DISP_EINK_UPDATE = 0x402,
	DISP_EINK_SET_TEMP = 0x403,
	DISP_EINK_GET_TEMP = 0x404,
	DISP_EINK_OVERLAP_SKIP = 0x405,
	DISP_EINK_UPDATE2 = 0x406,
};




  
#ifdef __cplusplus
extern "C" {
#endif	
int lcd_init(void);
int lcd_test(int idx, int r, int g, int b, int info);
int disp_ioctl(int rw, int value);
int disp_colorbar(int value);
#ifdef __cplusplus
}   // extern "C"
#endif

#endif	//__SPI_H__